## Assignment 2 | Data types

### Exercise 1. Create and Query a Dictionary on State Demographics

Based on the following table create two dictionaries, one for California and one for New York state. Each dictionary should have the following keys / value-type: name: (string) , population density: (float), race (dict), tenure: (dict). 

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other |
| --- | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 

1.  Create a dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [24]:
#Solution to 1:

CA={'name':'California', 'pop_density': 239.1,\
    'race': {'white': 0.57, 'african_american': 0.06, 'asian': 0.13, 'other': 0.22},\
    'tenure': {'owner': 7035371,'renter':5542127 }}
NY={'name':'New York', 'pop_density': 411.2,\
    'race': {'white': 0.65, 'african_american': 0.15, 'asian': 0.07, 'other': 0.22},\
    'tenure': {'owner': 3897837,'renter':3419918}}

    

In [25]:
states = {}
states["CA"] = CA
states["NY"] = NY
states

{'CA': {'name': 'California',
  'pop_density': 239.1,
  'race': {'white': 0.57,
   'african_american': 0.06,
   'asian': 0.13,
   'other': 0.22},
  'tenure': {'owner': 7035371, 'renter': 5542127}},
 'NY': {'name': 'New York',
  'pop_density': 411.2,
  'race': {'white': 0.65,
   'african_american': 0.15,
   'asian': 0.07,
   'other': 0.22},
  'tenure': {'owner': 3897837, 'renter': 3419918}}}

In [26]:
# Solution to 2
'Texas' in states

False

In [27]:
# Solution to 3
print(str((states)["NY"]["race"]["white"]*100)+'%')

65.0%


In [15]:
# Solution to 4
states["NY"]["race"]["white"]=.64
print(str((states)["NY"]["race"]["white"]*100)+'%')

64.0%


In [28]:
# Solution to 5
round(states["CA"]['tenure']['renter']/(states["CA"]['tenure']['owner']+states["CA"]['tenure']['renter'])*100,2)

44.06

### Exercise 2. Working with Numpy Arrays

1. Create a 4 x 4 array 'a' with the values of 3

1. Create a 4 x 4 array 'b' with elements drawn from a uniform random distribution 

1. Create array c by dividing a by b

1. Compute the min, mean, max, median and 90th percentile values of c

1. Compute the sum of the second column of c

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
# Solution to 6
a = np.ones(16).reshape(4,4)*3
a

array([[ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.]])

In [18]:
b = np.random.uniform(0,1,16).reshape(4,4)
b

array([[ 0.36137769,  0.76279374,  0.23788987,  0.03896025],
       [ 0.4450657 ,  0.62003187,  0.02049783,  0.1626561 ],
       [ 0.09550509,  0.77818221,  0.67565823,  0.78328095],
       [ 0.87472886,  0.6608229 ,  0.55906526,  0.45307746]])

In [19]:
c = a/b
c

array([[   8.30156391,    3.93291114,   12.61087737,   77.00156421],
       [   6.7405778 ,    4.83846093,  146.35695248,   18.44382063],
       [  31.4119395 ,    3.85513825,    4.44011465,    3.83004337],
       [   3.42963419,    4.53979428,    5.36609986,    6.62138435]])

In [20]:
c.mean()

21.357554807179895

In [21]:
c.min()

3.4296341877594605

In [22]:
c.max()

146.35695248286405

In [23]:
np.median(c)

5.9937421046378754

In [24]:
np.percentile(c,.9)

3.483689427756028

In [26]:
c[:,1].sum()

17.166304599797694